name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-creation.outputs.new_tag }}
      pyecvl_version: ${{ steps.get_pyecvl_version.outputs.pyecvl-version }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - id: get_pyecvl_version
      run: echo "::set-output name=pyecvl-version::$(cat requirements.txt | grep -oP 'pyecvl==\K(\d+\.\d+\.\d+)')"

    - run: echo "/opt/conda/bin:${PATH}" >> $GITHUB_PATH
    - run: sudo apt-get -y update && sudo apt-get -y install wget gcc && wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /opt/conda && export PATH=/opt/conda/bin:$PATH && conda update -y conda && conda install -y conda-build && conda update -y conda-build 
    - run: conda install -c anaconda python=3.6
    - run: conda install -c dhealth -c bioconda -c conda-forge pyecvl-cpu==${{ steps.get_pyecvl_version.outputs.pyecvl-version }}
    - run: export PATH=/opt/conda/bin:$PATH && pip install pytest wheel

    - name: test
      run: make test

    - name: Bump version and push tag
      id: tag-creation
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        RELEASE_BRANCHES: master


  docker:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
          tag: [gpu, cudnn]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: install
      run: make install

    - name: update VERSION file
      run: echo  "${{ needs.test.outputs.tag }}" > VERSION

    - name: set docker repo
      shell: bash
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: echo "$DOCKER_REPO" > docker/repo.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: build and push docker images
      env:
        BUILD_ARG: PARENT=dhealth/pylibs-toolkit:${{ needs.test.outputs.pyecvl_version }}-${{ matrix.tag }}
        EXTRA_TAGS: ${{ matrix.tag }}
      run: make docker-push skip_test=true


